app1/urls.py
from django.urls import path
from app1 import views

app_name = 'app1'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>',views.SchoolDetailView.as_view(),name='detail'),
    path('create',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>',views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',views.SchoolDeleteView.as_view(),name='delete'),
]

listdetailview/app1/urls.py
from django.urls import path
from app1 import views

app_name = 'app1'

urlpatterns = [
    path('',views.SchoolListView.as_view(),name='list'),
    path('<int:pk>',views.SchoolDetailView.as_view(),name='detail'),
    path('create',views.SchoolCreateView.as_view(),name='create'),
    path('update/<int:pk>',views.SchoolUpdateView.as_view(),name='update'),
    path('delete/<int:pk>',views.SchoolDeleteView.as_view(),name='delete'),
]

listdetailview/listdetailview/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import TemplateViewIndex

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',CBView.as_view()),
    path('',TemplateViewIndex.as_view()),
    path('app1/',include('app1.urls',namespace='app1')),
]

listdetailview/urls.py
from django.contrib import admin
from django.urls import path,include
from app1.views import TemplateViewIndex

urlpatterns = [
    path('admin/', admin.site.urls),
    #path('',CBView.as_view()),
    path('',TemplateViewIndex.as_view()),
    path('app1/',include('app1.urls',namespace='app1')),
]

app1/models.py
from pyexpat import model
from statistics import mode
from django.db import models
from django.urls import reverse

# Create your models here.


class School(models.Model):
    name = models.CharField(max_length=30)
    principal = models.CharField(max_length=30)
    loc = models.CharField(max_length=35)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("app1:detail",kwargs={'pk':self.pk})
        

class Student(models.Model):
    name = models.CharField(max_length=25)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,on_delete=models.CASCADE, related_name='students')

    def __str__(self):
        return self.name

listdetailview/app1/models.py
from pyexpat import model
from statistics import mode
from django.db import models
from django.urls import reverse

# Create your models here.


class School(models.Model):
    name = models.CharField(max_length=30)
    principal = models.CharField(max_length=30)
    loc = models.CharField(max_length=35)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("app1:detail",kwargs={'pk':self.pk})
        

class Student(models.Model):
    name = models.CharField(max_length=25)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School,on_delete=models.CASCADE, related_name='students')

    def __str__(self):
        return self.name

app1/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from django.views.generic import (View,
                                TemplateView,
                                ListView,
                                DetailView,
                                CreateView,
                                UpdateView,
                                DeleteView,)
from app1.models import School,Student
from django.urls import reverse_lazy
# Create your views here.

"""class CBView(View):
    def get(self,request):
        return HttpResponse("welcome")

class CBView2(View):
    def get(self,request):
        return HttpResponse("app1 page")"""

class TemplateViewIndex(TemplateView):
    template_name= "app1/index.html"

"""    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = "Django Data"
        return context"""

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = School
    template_name = 'app1/schoollist.html'

class SchoolDetailView(DetailView):
    context_object_name = 'schoolDetails'
    model = School
    template_name = 'app1/schooldetail.html'

class SchoolCreateView(CreateView):
    model = School
    fields = ('name','principal','loc')

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = School

class SchoolDeleteView(DeleteView):
    model = School
    success_url = reverse_lazy("app1:list")

listdetailview/app1/views.py
from http.client import HTTPResponse
from django.shortcuts import render
from django.views.generic import (View,
                                TemplateView,
                                ListView,
                                DetailView,
                                CreateView,
                                UpdateView,
                                DeleteView,)
from app1.models import School,Student
from django.urls import reverse_lazy
# Create your views here.

"""class CBView(View):
    def get(self,request):
        return HttpResponse("welcome")

class CBView2(View):
    def get(self,request):
        return HttpResponse("app1 page")"""

class TemplateViewIndex(TemplateView):
    template_name= "app1/index.html"

"""    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['msg'] = "Django Data"
        return context"""

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = School
    template_name = 'app1/schoollist.html'

class SchoolDetailView(DetailView):
    context_object_name = 'schoolDetails'
    model = School
    template_name = 'app1/schooldetail.html'

class SchoolCreateView(CreateView):
    model = School
    fields = ('name','principal','loc')

class SchoolUpdateView(UpdateView):
    fields = ('name','principal')
    model = School

class SchoolDeleteView(DeleteView):
    model = School
    success_url = reverse_lazy("app1:list")

listdetailview/templates/app1/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <style>
        header{
            text-align: center;
            color: red;
            background-color: aqua;
        }
        footer{
            text-align: center;
            color: red;
            background-color: grey;
            bottom: 0;
            width: 100%;
            position: fixed;
        }
        h2{
            text-align: center;
        }
        ul li{
            list-style-type: none;
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to Django Web Development</h1>
        <ul>
            <li><a href="{% url 'app1:list' %}">Schools</a></li>
        </ul>
    </header>
    <footer>
        <h1>Thanks for visiting</h1>
    </footer>
</body>
</html>

listdetailview/templates/app1/school_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <style>
        header{
            text-align: center;
            color: red;
            background-color: aqua;
        }
        footer{
            text-align: center;
            color: red;
            background-color: grey;
            bottom: 0;
            width: 100%;
            position: fixed;
        }
        h2{
            text-align: center;
        }
        ul li{
            list-style-type: none;
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to Django Web Development</h1>
        <ul>
            <li><a href="{% url 'app1:list' %}">Schools</a></li>
        </ul>
    </header>
    <h1>Delete {{school.name}}</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'app1:detail' pk=school.pk %}">Cancel</a>
    </form>
    <footer>
        <h1>Thanks for visiting</h1>
    </footer>
</body>
</html>

listdetailview/templates/app1/school_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SchoolForm</title>
</head>
<body>
    {% if not form.instance.pk %}
        Create School
    {% else %}
        Update School
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

listdetailview/templates/app1/schooldetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SchoolList</title>
    <style>
        header{
            text-align: center;
            color: red;
            background-color: aqua;
        }
        footer{
            text-align: center;
            color: red;
            background-color: grey;
            bottom: 0;
            width: 100%;
            position: fixed;
        }
        div{
            text-align: center;
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to Django Web Development</h1>
        <ul>
            <li><a href="{% url 'app1:list' %}">Schools</a></li>
        </ul>
    </header>
    <div>
        <p><a href="{% url 'app1:update' pk=schoolDetails.pk %}">Update</a></p>
        <p><a href="{% url 'app1:delete' pk=schoolDetails.pk %}">Delete</a></p>
    </div>
    <div>
        <h1>School Information</h1>
        <h2>School Name = {{schoolDetails.name}}</h2>
        <h2>School Principal = {{schoolDetails.principal}}</h2>
        <h2>Location = {{schoolDetails.loc}}</h2>
        <h1>Students Information</h1>
        {% for student in schoolDetails.students.all %}
            <h3>{{student.name}}</h3>
            <h3>{{student.age}}</h3>
        {% endfor %}
    </div>

    <footer>
        <h1>Thanks for visiting</h1>
    </footer>
</body>
</html>

listdetailview/templates/app1/schoollist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SchoolList</title>
    <style>
        header{
            text-align: center;
            color: red;
            background-color: aqua;
        }
        footer{
            text-align: center;
            color: red;
            background-color: grey;
            bottom: 0;
            width: 100%;
            position: fixed;
        }
        h2{
            text-align: center;
        }
        ol li{
            list-style-type: none;
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to Django Web Development</h1>
    </header>
    <div>
        <p><a href="{% url 'app1:create' %}">Insert</a></p>
    </div>
    <div>
        <ol>
            {% for school in schools %}
                <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
            {% endfor %}
        </ol>
    </div>
    <footer>
        <h1>Thanks for visiting</h1>
    </footer>
</body>
</html>

templates/app1/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <style>
        header{
            text-align: center;
            color: red;
            background-color: aqua;
        }
        footer{
            text-align: center;
            color: red;
            background-color: grey;
            bottom: 0;
            width: 100%;
            position: fixed;
        }
        h2{
            text-align: center;
        }
        ul li{
            list-style-type: none;
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to Django Web Development</h1>
        <ul>
            <li><a href="{% url 'app1:list' %}">Schools</a></li>
        </ul>
    </header>
    <footer>
        <h1>Thanks for visiting</h1>
    </footer>
</body>
</html>

templates/app1/school_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Index</title>
    <style>
        header{
            text-align: center;
            color: red;
            background-color: aqua;
        }
        footer{
            text-align: center;
            color: red;
            background-color: grey;
            bottom: 0;
            width: 100%;
            position: fixed;
        }
        h2{
            text-align: center;
        }
        ul li{
            list-style-type: none;
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to Django Web Development</h1>
        <ul>
            <li><a href="{% url 'app1:list' %}">Schools</a></li>
        </ul>
    </header>
    <h1>Delete {{school.name}}</h1>
    <form method="post">
        {% csrf_token %}
        <input type="submit" value="Delete">
        <a href="{% url 'app1:detail' pk=school.pk %}">Cancel</a>
    </form>
    <footer>
        <h1>Thanks for visiting</h1>
    </footer>
</body>
</html>

templates/app1/school_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SchoolForm</title>
</head>
<body>
    {% if not form.instance.pk %}
        Create School
    {% else %}
        Update School
    {% endif %}
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit">
    </form>
</body>
</html>

templates/app1/schooldetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SchoolList</title>
    <style>
        header{
            text-align: center;
            color: red;
            background-color: aqua;
        }
        footer{
            text-align: center;
            color: red;
            background-color: grey;
            bottom: 0;
            width: 100%;
            position: fixed;
        }
        div{
            text-align: center;
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to Django Web Development</h1>
        <ul>
            <li><a href="{% url 'app1:list' %}">Schools</a></li>
        </ul>
    </header>
    <div>
        <p><a href="{% url 'app1:update' pk=schoolDetails.pk %}">Update</a></p>
        <p><a href="{% url 'app1:delete' pk=schoolDetails.pk %}">Delete</a></p>
    </div>
    <div>
        <h1>School Information</h1>
        <h2>School Name = {{schoolDetails.name}}</h2>
        <h2>School Principal = {{schoolDetails.principal}}</h2>
        <h2>Location = {{schoolDetails.loc}}</h2>
        <h1>Students Information</h1>
        {% for student in schoolDetails.students.all %}
            <h3>{{student.name}}</h3>
            <h3>{{student.age}}</h3>
        {% endfor %}
    </div>

    <footer>
        <h1>Thanks for visiting</h1>
    </footer>
</body>
</html>

templates/app1/schoollist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SchoolList</title>
    <style>
        header{
            text-align: center;
            color: red;
            background-color: aqua;
        }
        footer{
            text-align: center;
            color: red;
            background-color: grey;
            bottom: 0;
            width: 100%;
            position: fixed;
        }
        h2{
            text-align: center;
        }
        ol li{
            list-style-type: none;
        }
    </style>
</head>
<body>
    <header>
        <h1>Welcome to Django Web Development</h1>
    </header>
    <div>
        <p><a href="{% url 'app1:create' %}">Insert</a></p>
    </div>
    <div>
        <ol>
            {% for school in schools %}
                <h2><li><a href="{{school.id}}">{{school.name}}</a></li></h2>
            {% endfor %}
        </ol>
    </div>
    <footer>
        <h1>Thanks for visiting</h1>
    </footer>
</body>
</html>